package my.animalApp;
import javax.swing.JOptionPane;
public class AnimalGUI extends javax.swing.JFrame {
    // create animal array
            private static Animal[] animals = new Animal[3];
            private int count = 0;
            
    /**
     * Creates new form AnimalGUI
     */
    public AnimalGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        animalButtonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        colourTF = new javax.swing.JTextField();
        legsTF = new javax.swing.JTextField();
        soundTF = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display1 = new javax.swing.JTextArea();
        displayBtn = new javax.swing.JButton();
        catButton1 = new javax.swing.JRadioButton();
        bearButton2 = new javax.swing.JRadioButton();
        elephantButton3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\t\t\tAnimal Family");
        setLocation(new java.awt.Point(500, 500));

        jLabel1.setText("INPUT");

        jLabel2.setText("OUTPUT");

        jLabel3.setText("Name: ");

        jLabel4.setText("Colour: ");

        jLabel5.setText("Legs: ");

        jLabel6.setText("Sound:");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear All");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        display1.setColumns(20);
        display1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        display1.setForeground(new java.awt.Color(255, 255, 255));
        display1.setRows(5);
        display1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        display1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        display1.setEnabled(false);
        jScrollPane1.setViewportView(display1);

        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        animalButtonGroup1.add(catButton1);
        catButton1.setText("Cat");
        catButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catButton1ActionPerformed(evt);
            }
        });

        animalButtonGroup1.add(bearButton2);
        bearButton2.setText("Bear");

        animalButtonGroup1.add(elephantButton3);
        elephantButton3.setText("Elephant");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(saveBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(clearBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(exitBtn))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(soundTF, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(legsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(colourTF, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(catButton1)
                            .addGap(43, 43, 43)
                            .addComponent(bearButton2)
                            .addGap(37, 37, 37)
                            .addComponent(elephantButton3)))
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayBtn))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(catButton1)
                            .addComponent(bearButton2))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(colourTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(legsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(soundTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveBtn)
                            .addComponent(clearBtn)
                            .addComponent(exitBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(elephantButton3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(displayBtn)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catButton1ActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Do you want to quit?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(response == JOptionPane.YES_OPTION){
        System.exit(0);
        }
        else if (response == JOptionPane.NO_OPTION){
        JOptionPane.getRootFrame().dispose();   
        }
        
    }//GEN-LAST:event_exitBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Do you want to clear all the fields?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(response == JOptionPane.YES_OPTION){
        animalButtonGroup1.clearSelection();
        nameTF.setText("");
        colourTF.setText("");
        legsTF.setText("");
        soundTF.setText("");
        display1.setText("");
        }
        else if (response == JOptionPane.NO_OPTION){
        JOptionPane.getRootFrame().dispose();   
        }       
    }//GEN-LAST:event_clearBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        display1.setText("");
        
        if(count == animals.length){
        display1.setText("Error. Sorry, list is Full!");
        animalButtonGroup1.clearSelection();
        nameTF.setText("");
        colourTF.setText("");
        legsTF.setText("");
        soundTF.setText("");
        return;
        }
        
        if (catButton1.isSelected()){
        //reading input
        String nameText = nameTF.getText();
        String colourText = colourTF.getText();
        String legsText = legsTF.getText();
        String soundText = soundTF.getText();
        int legs =0;
        try { 
             legs = Integer.parseInt(legsText);
  
            } 
        catch ( NumberFormatException e ) { 
            display1.setText("Error. Invalid input for legs.");
            return;
            } 
        
        animals [count] = new Cat (nameText, legs, soundText, colourText);
        count++;
        animalButtonGroup1.clearSelection();
        nameTF.setText("");
        colourTF.setText("");
        legsTF.setText("");
        soundTF.setText("");
        }
        else if (bearButton2.isSelected()){
        //reading input
        String nameText = nameTF.getText();
        String colourText = colourTF.getText();
        String legsText = legsTF.getText();
        String soundText = soundTF.getText();
        int legs =0;
        try { 
             legs = Integer.parseInt(legsText);
  
            } 
        catch ( NumberFormatException e ) { 
            display1.setText("Error. Invalid input for legs.");
            return;
            }
            
        animals [count] = new Bear (nameText, legs, soundText, colourText);
        count++;
        animalButtonGroup1.clearSelection();
        nameTF.setText("");
        colourTF.setText("");
        legsTF.setText("");
        soundTF.setText("");
        }
        else if (elephantButton3.isSelected()){
        //reading input
        String nameText = nameTF.getText();
        String colourText = colourTF.getText();
        String legsText = legsTF.getText();
        String soundText = soundTF.getText();
        int legs =0;
        try { 
             legs = Integer.parseInt(legsText);
  
            } 
        catch ( NumberFormatException e ) { 
            display1.setText("Error. Invalid input for legs.");
            return;
            }
        
        animals [count] = new Elephant (nameText, legs, soundText, colourText);
        count++;
        animalButtonGroup1.clearSelection();
        nameTF.setText("");
        colourTF.setText("");
        legsTF.setText("");
        soundTF.setText("");
        }    
    }//GEN-LAST:event_saveBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
            display1.setText("");
            display1.setLineWrap(true);
            display1.setWrapStyleWord(true);
            
            if(count == 0){
                display1.setText("Error. Sorry list is empty!");
                animalButtonGroup1.clearSelection();
                nameTF.setText("");
                colourTF.setText("");
                legsTF.setText("");
                soundTF.setText("");
                }
            
            else
            for (int i = 0;i<count; i++){
                
            
                if(animals[i] instanceof Cat){
                display1.append("---------------CAT---------------\n");     
                display1.append(animals[i].display()+ "\n");    
                display1.append(animals[i].getName()+ " is a " + ((Cat)animals[i]).typeC() + " and " + ((Cat)animals[i]).foodC() + "\n");
                display1.append(((Cat)animals[i]).eat() + "\n"); 
                display1.append(((Cat)animals[i]).play() + "\n"); 

                }
                else if (animals[i] instanceof Bear){
                display1.append("---------------BEAR---------------\n");     
                display1.append(animals[i].display()+ "\n");    
                display1.append("Bear is an " + ((Bear)animals[i]).typeO()+ "\n");
                display1.append(((Bear)animals[i]).descO() + "\n"); 
                display1.append(((Bear)animals[i]).eat() + "\n");
                }
                        
                else if (animals[i] instanceof Elephant){
                display1.append("---------------ELEPHANT---------------\n");     
                display1.append(animals[i].display()+ "\n");    
                display1.append(animals[i].getName()+ " is a " + ((Elephant)animals[i]).typeH() + " and " + ((Elephant)animals[i]).foodH() + "\n");
                display1.append(((Elephant)animals[i]).eat() + "\n"); 
                }      
    }//GEN-LAST:event_displayBtnActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimalGUI().setVisible(true);
            }
                

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup animalButtonGroup1;
    private javax.swing.JRadioButton bearButton2;
    private javax.swing.JRadioButton catButton1;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField colourTF;
    private javax.swing.JTextArea display1;
    private javax.swing.JButton displayBtn;
    private javax.swing.JRadioButton elephantButton3;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField legsTF;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField soundTF;
    // End of variables declaration//GEN-END:variables
}
