/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.PibgVoteApp;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static my.PibgVoteApp.MainMenuGUI.CandidateListHolder.list;
import static my.PibgVoteApp.MainMenuGUI.VoterListHolder.voterlist;

/**
 *
 * @author User
 */
public class adminGUI extends javax.swing.JFrame {

    private static adminGUI adminInstance;
    int candidateIndex;

    /**
     * Creates new form adminGUI
     */
    public adminGUI() {
        initComponents();
        setImage();
        adminInstance = this;
        insertCandidate();
        checkUpDelTime();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CandUpdate = new javax.swing.JDialog();
        CancelBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        UpdateConBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nameUpdate = new javax.swing.JTextField();
        ageUpdate = new javax.swing.JTextField();
        jobUpdate = new javax.swing.JTextField();
        expUpdate = new javax.swing.JTextField();
        bestUpdate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ageLabel1 = new javax.swing.JLabel();
        expLbl1 = new javax.swing.JLabel();
        UpdateIndex = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        txtUpdate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CancelBtn1 = new javax.swing.JButton();
        ConBtn1 = new javax.swing.JButton();
        updateLbl = new javax.swing.JLabel();
        DelIndex = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        txtCandelete = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CancelBtn2 = new javax.swing.JButton();
        DelConBtn1 = new javax.swing.JButton();
        dltLbl = new javax.swing.JLabel();
        CandDel = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        occLabel = new javax.swing.JLabel();
        expLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        canBtn = new javax.swing.JButton();
        bestLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        DelCfmBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        searchBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        resetBtn = new javax.swing.JButton();
        exportBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        displayVoteBtn = new javax.swing.JButton();
        displayCanBtn = new javax.swing.JButton();
        displayResultsBtn = new javax.swing.JButton();
        adminExitBtn = new javax.swing.JButton();
        adminBackBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        CandUpdate.setTitle("Update Candidate Information");

        CancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Name:");

        UpdateConBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateConBtn.setText("Confirm ");
        UpdateConBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateConBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Occupation:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Experience (in Years):");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Age:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Best Related Experience:");

        nameUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameUpdateActionPerformed(evt);
            }
        });

        ageUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageUpdateKeyPressed(evt);
            }
        });

        expUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                expUpdateKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("Candidate Information Update");

        ageLabel1.setForeground(new java.awt.Color(255, 0, 0));

        expLbl1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout CandUpdateLayout = new javax.swing.GroupLayout(CandUpdate.getContentPane());
        CandUpdate.getContentPane().setLayout(CandUpdateLayout);
        CandUpdateLayout.setHorizontalGroup(
            CandUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CandUpdateLayout.createSequentialGroup()
                .addGroup(CandUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CandUpdateLayout.createSequentialGroup()
                        .addGroup(CandUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CandUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CandUpdateLayout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(CandUpdateLayout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addGroup(CandUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(CandUpdateLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(CandUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameUpdate)
                            .addComponent(ageUpdate)
                            .addComponent(jobUpdate)
                            .addComponent(expUpdate)
                            .addComponent(bestUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CandUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(expLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                    .addGroup(CandUpdateLayout.createSequentialGroup()
                        .addGroup(CandUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CandUpdateLayout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(171, 171, 171)
                                .addComponent(UpdateConBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CandUpdateLayout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CandUpdateLayout.setVerticalGroup(
            CandUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CandUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(CandUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(CandUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLabel1)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(CandUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jobUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(CandUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expLbl1)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(CandUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bestUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(62, 62, 62)
                .addGroup(CandUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateConBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        UpdateIndex.setTitle("Update Candidate Information");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Candidate Information Update");

        txtUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUpdateKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Candidate No:");

        CancelBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CancelBtn1.setText("Cancel");
        CancelBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtn1ActionPerformed(evt);
            }
        });

        ConBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConBtn1.setText("Confirm ");
        ConBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConBtn1ActionPerformed(evt);
            }
        });

        updateLbl.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout UpdateIndexLayout = new javax.swing.GroupLayout(UpdateIndex.getContentPane());
        UpdateIndex.getContentPane().setLayout(UpdateIndexLayout);
        UpdateIndexLayout.setHorizontalGroup(
            UpdateIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateIndexLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(CancelBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ConBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(UpdateIndexLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(UpdateIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(txtUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        UpdateIndexLayout.setVerticalGroup(
            UpdateIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateIndexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(UpdateIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        DelIndex.setTitle("Delete Candidate Information");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Delete Candidate");

        txtCandelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCandeleteKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Candidate No:");

        CancelBtn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CancelBtn2.setText("Cancel");
        CancelBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtn2ActionPerformed(evt);
            }
        });

        DelConBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DelConBtn1.setText("Confirm ");
        DelConBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelConBtn1ActionPerformed(evt);
            }
        });

        dltLbl.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout DelIndexLayout = new javax.swing.GroupLayout(DelIndex.getContentPane());
        DelIndex.getContentPane().setLayout(DelIndexLayout);
        DelIndexLayout.setHorizontalGroup(
            DelIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DelIndexLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(CancelBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DelConBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(DelIndexLayout.createSequentialGroup()
                .addGroup(DelIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DelIndexLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(DelIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtCandelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dltLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DelIndexLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel3)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        DelIndexLayout.setVerticalGroup(
            DelIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DelIndexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCandelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dltLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(DelIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DelConBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        CandDel.setTitle("Delete Candidate Information");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel12.setText("Candidate Deletion Confirmation");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Experience (in Years):");

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameLabel.setText("jLabel10");
        nameLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ageLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ageLabel.setText("jLabel11");
        ageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        occLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        occLabel.setText("jLabel12");
        occLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        expLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        expLabel.setText("jLabel13");
        expLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Age:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Best Related Experience:");

        canBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        canBtn.setText("Cancel");
        canBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canBtnActionPerformed(evt);
            }
        });

        bestLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bestLabel.setText("jLabel14");
        bestLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Name:");

        DelCfmBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DelCfmBtn.setText("Confirm ");
        DelCfmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelCfmBtnActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Occupation:");

        javax.swing.GroupLayout CandDelLayout = new javax.swing.GroupLayout(CandDel.getContentPane());
        CandDel.getContentPane().setLayout(CandDelLayout);
        CandDelLayout.setHorizontalGroup(
            CandDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CandDelLayout.createSequentialGroup()
                .addGroup(CandDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CandDelLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(canBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171)
                        .addComponent(DelCfmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CandDelLayout.createSequentialGroup()
                        .addGroup(CandDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CandDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CandDelLayout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(CandDelLayout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addGroup(CandDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(CandDelLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(CandDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CandDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(expLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(occLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CandDelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(223, 223, 223))
        );
        CandDelLayout.setVerticalGroup(
            CandDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CandDelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(CandDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(nameLabel))
                .addGap(14, 14, 14)
                .addGroup(CandDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(CandDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(occLabel)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(CandDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(expLabel))
                .addGap(18, 18, 18)
                .addGroup(CandDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(bestLabel))
                .addGap(61, 61, 61)
                .addGroup(CandDelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DelCfmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Page");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        searchBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchBtn)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Reset/Export", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N

        resetBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        exportBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        exportBtn.setText("Export");
        exportBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(exportBtn)
                .addGap(18, 18, 18)
                .addComponent(resetBtn)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Display", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18)))); // NOI18N

        txtOutput.setEditable(false);
        txtOutput.setColumns(20);
        txtOutput.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        displayVoteBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        displayVoteBtn.setText("Display Voter");
        displayVoteBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        displayVoteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayVoteBtnActionPerformed(evt);
            }
        });

        displayCanBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        displayCanBtn.setText("Display Candidate");
        displayCanBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        displayCanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCanBtnActionPerformed(evt);
            }
        });

        displayResultsBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        displayResultsBtn.setText("Display Results");
        displayResultsBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        displayResultsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayResultsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(displayCanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayResultsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayVoteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayVoteBtn)
                    .addComponent(displayCanBtn)
                    .addComponent(displayResultsBtn))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        adminExitBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        adminExitBtn.setText("Exit");
        adminExitBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adminExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminExitBtnActionPerformed(evt);
            }
        });

        adminBackBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        adminBackBtn.setText("Back");
        adminBackBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adminBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBackBtnActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Update/Delete ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N

        updateBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(updateBtn)
                .addGap(18, 18, 18)
                .addComponent(deleteBtn)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(adminBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminExitBtn)
                    .addComponent(adminBackBtn))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        DelIndex.setVisible(true);
        DelIndex.setSize(400, 300);
        DelIndex.setLocationRelativeTo(null);
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void adminBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBackBtnActionPerformed
        // TODO add your handling code here:
        adminGUI.closeAdmin();
        new MainMenuGUI().setVisible(true);
    }//GEN-LAST:event_adminBackBtnActionPerformed

    private void adminExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminExitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_adminExitBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String selectedName = (String) jComboBox1.getSelectedItem();
        String text = "Voters:\n=======================\n";
        if (selectedName.equals("All Candidates")) {
            for (Voter v : voterlist) {
                if (!v.getVoted().equals("-")) {
                    text += "Name: " + v.getName() + "\nIcNo: " + v.getIcNo() + "\nVoted for: " + v.getVoted() + "\n=======================\n";
                }
            }
        } else {
            for (Voter v : voterlist) {
                if (v.getVoted().equals(selectedName)) {
                    text += "Name: " + v.getName() + "\nIcNo: " + v.getIcNo() + "\nVoted for: " + v.getVoted() + "\n=======================\n";
                }
            }
        }
        txtOutput.setText(text);
        txtOutput.setCaretPosition(0);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void displayVoteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayVoteBtnActionPerformed
        // TODO add your handling code here:
        String text = "Voters:\n=======================\n";
        for (Voter v : voterlist) {
            text += "Name: " + v.getName() + "\nIcNo: " + v.getIcNo() + "\nVoted for: " + v.getVoted() + "\n=======================\n";
        }
        txtOutput.setText(text);
        txtOutput.setCaretPosition(0);
    }//GEN-LAST:event_displayVoteBtnActionPerformed

    private void displayCanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayCanBtnActionPerformed
        // TODO add your handling code here:
        txtOutput.setText("Candidates:\n=======================\n");
        int candidateNum = 1;
        for (Candidate c : list) {
            String row = String.format("Candidate No: %-5d\nName: %-15s\nAge: %-5d\nJob: %-25s\nExperience: %-5d\nAchievements: %s\n", candidateNum, c.getName(), c.getAge(), c.getJob(), c.getExperience(), c.getAchievements());
            txtOutput.append(row);
            txtOutput.append("=======================\n");
            candidateNum++;
            txtOutput.setCaretPosition(0);
        }
    }//GEN-LAST:event_displayCanBtnActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        // TODO add your handling code here:
        CandUpdate.setVisible(false);
        new adminGUI().setVisible(true);
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void UpdateConBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateConBtnActionPerformed
        // TODO add your handling code here:
        list.set(candidateIndex, new Candidate(nameUpdate.getText(), Integer.parseInt(ageUpdate.getText()), jobUpdate.getText(), Integer.parseInt(expUpdate.getText()), bestUpdate.getText()));

        FileWriter writer;
        try {
            writer = new FileWriter("Candidate.txt");
            for (Candidate c : list) {
                String candidateInfo = c.getName() + "," + c.getAge() + "," + c.getJob() + "," + c.getExperience() + "," + c.getAchievements() + "\n";
                writer.write(candidateInfo);
            }
            writer.close();
            Object[] options = {"OK"};
            JOptionPane.showOptionDialog(this, "The Candidate Information has been updated!", "Information Update",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
                    null, options, options[0]);
            CandUpdate.setVisible(false);
            new adminGUI().setVisible(true);

        } catch (IOException ex) {
            Logger.getLogger(CandidateReg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateConBtnActionPerformed

    private void nameUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameUpdateActionPerformed

    private void CancelBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtn1ActionPerformed
        // TODO add your handling code here:
        UpdateIndex.setVisible(false);
    }//GEN-LAST:event_CancelBtn1ActionPerformed

    private void ConBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConBtn1ActionPerformed
        // TODO add your handling code here:
        try {
            int index = Integer.parseInt(txtUpdate.getText()) - 1;
            if (index >= 0 && index < list.size()) {
                Candidate c = list.get(index);
                int candidateIndex = list.indexOf(c);
                setCandidateDetails(c, candidateIndex);
                UpdateIndex.setVisible(false);
                adminGUI.closeAdmin();
                CandUpdate.setVisible(true);
                CandUpdate.setSize(740, 430);
                CandUpdate.setLocationRelativeTo(null);
            } else {
                Object[] options = {"OK"};
                JOptionPane.showOptionDialog(this, "Candidate not found, Please enter again!", "Error",
                        JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
                        null, options, options[0]);

                txtUpdate.setText("");
            }
        } catch (NumberFormatException e) {

            Object[] options = {"OK"};
            JOptionPane.showOptionDialog(this, "Please enter a valid candidate number!", "Error",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
                    null, options, options[0]);

            txtUpdate.setText("");
        }


    }//GEN-LAST:event_ConBtn1ActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:

        UpdateIndex.setVisible(true);
        UpdateIndex.setSize(400, 300);
        UpdateIndex.setLocationRelativeTo(null);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void CancelBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtn2ActionPerformed
        // TODO add your handling code here:
        DelIndex.setVisible(false);
    }//GEN-LAST:event_CancelBtn2ActionPerformed

    private void DelConBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelConBtn1ActionPerformed
        // TODO add your handling code here:
        try {
            int index = Integer.parseInt(txtCandelete.getText()) - 1;
            if (index >= 0 && index < list.size()) {
                Candidate c = list.get(index);
                int candidateIndex = list.indexOf(c);
                setDelCandidateDetails(c, candidateIndex);
                adminGUI.closeAdmin();
                DelIndex.setVisible(false);
                CandDel.setVisible(true);
                CandDel.setSize(740, 430);
                CandDel.setLocationRelativeTo(null);

            } else {
                Object[] options = {"OK"};
                JOptionPane.showOptionDialog(this, "Candidate not found, Please enter again!", "Error",
                        JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
                        null, options, options[0]);

                txtCandelete.setText("");
            }
        } catch (NumberFormatException e) {

            Object[] options = {"OK"};
            JOptionPane.showOptionDialog(this, "Please enter a valid candidate number!", "Error",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
                    null, options, options[0]);

            txtCandelete.setText("");
        }
    }//GEN-LAST:event_DelConBtn1ActionPerformed

    private void canBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canBtnActionPerformed
        // TODO add your handling code here:
        CandDel.setVisible(false);
        new adminGUI().setVisible(true);
    }//GEN-LAST:event_canBtnActionPerformed

    private void DelCfmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelCfmBtnActionPerformed
        // TODO add your handling code here:
        list.remove(candidateIndex);

        FileWriter writer;
        try {
            writer = new FileWriter("Candidate.txt");
            for (Candidate c : list) {
                String candidateInfo = c.getName() + "," + c.getAge() + "," + c.getJob() + "," + c.getExperience() + "," + c.getAchievements() + "\n";
                writer.write(candidateInfo);
            }
            writer.close();
            Object[] options = {"OK"};
            JOptionPane.showOptionDialog(this, "The Candidate Information has been deleted!", "Information Delete",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
                    null, options, options[0]);
            CandDel.setVisible(false);
            new adminGUI().setVisible(true);

        } catch (IOException ex) {
            Logger.getLogger(CandidateReg.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_DelCfmBtnActionPerformed

    private void exportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser("C:/Users/vince/OneDrive/Desktop");
        chooser.setDialogType(JFileChooser.SAVE_DIALOG);
        chooser.setSelectedFile(new File("MyFile.txt"));
        int result = chooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            // Save the file at the selected location
            try {
                FileWriter writer = new FileWriter(selectedFile);
                writer.write(txtOutput.getText());
                writer.close();
                Object[] options = {"OK"};
                JOptionPane.showOptionDialog(null, "File saved successfully!", "Success", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
                txtOutput.setText("");
            } catch (IOException ex) {
                JOptionPane.showOptionDialog(null, "Error saving file!", "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE, null, new Object[]{}, null);
            }
        }
    }//GEN-LAST:event_exportBtnActionPerformed

    private void displayResultsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayResultsBtnActionPerformed
        // TODO add your handling code here:
        // Create an array to store the vote counts for each candidate
        int[] voteCounts = new int[list.size()];

        // Iterate through the voter list and count the votes for each candidate
        for (Voter v : voterlist) {
            for (int i = 0; i < list.size(); i++) {
                if (v.getVoted().equals(list.get(i).getName())) {
                    voteCounts[i]++;
                }
            }
        }
        // Display the results in the txtOutput text area
        txtOutput.setText("Results:\n=======================\n");
        for (int i = 0; i < list.size(); i++) {
            txtOutput.append(list.get(i).getName() + ": " + voteCounts[i] + " votes\n");
        }
        txtOutput.setCaretPosition(0);
    }//GEN-LAST:event_displayResultsBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Do you want to reset all the information?", "Reset", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            try {
                list.clear();
                FileWriter fw = new FileWriter("Candidate.txt", false);
                fw.write("");
                fw.close();
                FileWriter vw = new FileWriter("voter.txt", false);
                vw.write("");
                vw.close();
                voterlist.clear();
                txtOutput.setText("");

                JOptionPane.showMessageDialog(null, "Information reset successfully");
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else if (choice == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Reset canceled");
        }
    }//GEN-LAST:event_resetBtnActionPerformed

    private void ageUpdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageUpdateKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c) || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE) {
            ageUpdate.setEditable(true);
            ageLabel1.setText("");
        } else {
            ageUpdate.setEditable(false);
            ageLabel1.setText("Please Enter Numbers Only!");
        }
    }//GEN-LAST:event_ageUpdateKeyPressed

    private void expUpdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expUpdateKeyPressed
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if (Character.isDigit(ch) || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE) {
            expUpdate.setEditable(true);
            expLbl1.setText("");
        } else {
            expUpdate.setEditable(false);
            expLbl1.setText("Please Enter Numbers Only!");
        }
    }//GEN-LAST:event_expUpdateKeyPressed

    private void txtUpdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUpdateKeyPressed
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if (Character.isDigit(ch) || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE) {
            txtUpdate.setEditable(true);
            updateLbl.setText("");
        } else {
            txtUpdate.setEditable(false);
            updateLbl.setText("Please Enter Numbers Only!");
        }
    }//GEN-LAST:event_txtUpdateKeyPressed

    private void txtCandeleteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCandeleteKeyPressed
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if (Character.isDigit(ch) || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE) {
            txtCandelete.setEditable(true);
            dltLbl.setText("");
        } else {
            txtCandelete.setEditable(false);
            dltLbl.setText("Please Enter Numbers Only!");
        }
    }//GEN-LAST:event_txtCandeleteKeyPressed

    public static void closeAdmin() {
        adminInstance.setVisible(false);
    }

    private void insertCandidate() {
        jComboBox1.addItem("All Candidates");
        for (Candidate c : list) {
            jComboBox1.addItem(c.getName());
        }
    }

    public void setCandidateDetails(Candidate c, int candidateIndex) {
        // set the details of the candidate object to the textfields
        nameUpdate.setText(c.getName());
        ageUpdate.setText(Integer.toString(c.getAge()));
        jobUpdate.setText(c.getJob());
        expUpdate.setText(Integer.toString(c.getExperience()));
        bestUpdate.setText(c.getAchievements());
        this.candidateIndex = candidateIndex;
    }

    public void setDelCandidateDetails(Candidate c, int candidateIndex) {
        // set the details of the candidate object to the textfields
        nameLabel.setText(c.getName());
        ageLabel.setText(Integer.toString(c.getAge()));
        occLabel.setText(c.getJob());
        expLabel.setText(Integer.toString(c.getExperience()));
        bestLabel.setText(c.getAchievements());
        this.candidateIndex = candidateIndex;
    }

    public void checkUpDelTime() {
        LocalDateTime now = LocalDateTime.now();
        if (Timeline.isRegistrationPeriodActive()) {
            updateBtn.setEnabled(true);
            deleteBtn.setEnabled(true);

        } else if (Timeline.isVotingPeriodActive()) {
            updateBtn.setEnabled(false);
            deleteBtn.setEnabled(false);
        }

    }

    public void setImage() {
        Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("sekolah-tinggi-klang-logo-DBDC58156C-seeklogo.com.png"));
        ImageIcon icon = new ImageIcon(image);
        setIconImage(icon.getImage());
        CandUpdate.setIconImage(icon.getImage());
        UpdateIndex.setIconImage(icon.getImage());
        CandDel.setIconImage(icon.getImage());
        DelIndex.setIconImage(icon.getImage());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JButton CancelBtn1;
    private javax.swing.JButton CancelBtn2;
    private javax.swing.JDialog CandDel;
    private javax.swing.JDialog CandUpdate;
    private javax.swing.JButton ConBtn1;
    private javax.swing.JButton DelCfmBtn;
    private javax.swing.JButton DelConBtn1;
    private javax.swing.JDialog DelIndex;
    private javax.swing.JButton UpdateConBtn;
    private javax.swing.JDialog UpdateIndex;
    private javax.swing.JButton adminBackBtn;
    private javax.swing.JButton adminExitBtn;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel ageLabel1;
    private javax.swing.JTextField ageUpdate;
    private javax.swing.JLabel bestLabel;
    private javax.swing.JTextField bestUpdate;
    private javax.swing.JButton canBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayCanBtn;
    private javax.swing.JButton displayResultsBtn;
    private javax.swing.JButton displayVoteBtn;
    private javax.swing.JLabel dltLbl;
    private javax.swing.JLabel expLabel;
    private javax.swing.JLabel expLbl1;
    private javax.swing.JTextField expUpdate;
    private javax.swing.JButton exportBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jobUpdate;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameUpdate;
    private javax.swing.JLabel occLabel;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField txtCandelete;
    private javax.swing.JTextArea txtOutput;
    private javax.swing.JTextField txtUpdate;
    private javax.swing.JButton updateBtn;
    private javax.swing.JLabel updateLbl;
    // End of variables declaration//GEN-END:variables
}
