/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.PibgVoteApp;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import my.PibgVoteApp.MainMenuGUI.CandidateListHolder;
import static my.PibgVoteApp.MainMenuGUI.VoterListHolder.voterlist;

/**
 *
 * @author vince
 */
public class VoteGUI extends javax.swing.JFrame {

    private String name;
    private String icNo;
    private static VoteGUI voteInstance;
    ArrayList<Candidate> list = CandidateListHolder.list;

    /**
     * Creates new form VoteGUI
     */
    public VoteGUI(String name, String icNo) {
        this.name = name;
        this.icNo = icNo;
        initComponents();
        setImage();
        voteInstance = this;
        display();
        insertCandidate();
    }

    @Override
    protected void processWindowEvent(WindowEvent e) {
        if (e.getID() == WindowEvent.WINDOW_CLOSING) {
            // prevent the window from being closed
            Object[] options = {"OK"};
            JOptionPane.showOptionDialog(this, "You are not allowed to exit!", "NO EXIT",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
                    null, options, options[0]);
            return;
        }
        super.processWindowEvent(e);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CandidateRegLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        voteBack = new javax.swing.JButton();
        voteSave = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Voting");

        CandidateRegLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        CandidateRegLabel.setText("Vote");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        voteBack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        voteBack.setText("Back");
        voteBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        voteBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voteBackActionPerformed(evt);
            }
        });

        voteSave.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        voteSave.setText("Save");
        voteSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        voteSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voteSaveActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Select Your Desired Candidate:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(voteBack, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(526, 526, 526)
                        .addComponent(voteSave, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(CandidateRegLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CandidateRegLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voteSave, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voteBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voteBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteBackActionPerformed
        // TODO add your handling code here:
        //back
        VoteGUI.closeVoteGUI();
        new MainMenuGUI().setVisible(true);
    }//GEN-LAST:event_voteBackActionPerformed

    private void voteSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteSaveActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Do you want to proceed with your vote?", "Confirm Vote", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {

            String selectedName = (String) jComboBox1.getSelectedItem();
            for (Voter v : voterlist) {
                if (v.getName().toLowerCase().trim().equals(name.toLowerCase().trim()) && v.getIcNo().toLowerCase().trim().equals(icNo.toLowerCase().trim())) {
                    // Update the "voted" attribute of the voter object
                    v.setVoted(selectedName);

                    try ( BufferedWriter bw = new BufferedWriter(new FileWriter("voter.txt"))) {
                        for (Voter voter : voterlist) {
                            bw.write(voter.getName() + "," + voter.getIcNo() + "," + voter.getVoted());
                            bw.newLine();
                        }
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            }
            Object[] options = {"OK"};
            JOptionPane.showOptionDialog(this, "You vote has been recorded!", "Vote Successful",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
                    null, options, options[0]);

            VoteGUI.closeVoteGUI();
            new MainMenuGUI().setVisible(true);

        } else if (response == JOptionPane.NO_OPTION) {
            JOptionPane.getRootFrame().dispose();
        }


    }//GEN-LAST:event_voteSaveActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public static void closeVoteGUI() {
        voteInstance.setVisible(false);
    }

    private void display() {
        // Clear the text area
        jTextArea1.setText("");

        // Print the table header
        String header = String.format("%-5s %-15s %-5s %-25s %-5s %s\n", "No.", "Name", "Age", "Job", "Exp.", "Achievements");
        jTextArea1.append(header);
        jTextArea1.append("--------------------------------------------------------------------------------------------\n");

        // Print each object in the list, including the candidate number
        int candidateNum = 1;
        for (Candidate c : list) {
            String row = String.format("%-5d %-15s %-5d %-25s %-5d %s\n", candidateNum, c.getName(), c.getAge(), c.getJob(), c.getExperience(), c.getAchievements());
            jTextArea1.append(row);
            candidateNum++;
        }
    }

    private void insertCandidate() {
        for (Candidate c : list) {
            jComboBox1.addItem(c.getName());
        }
    }

    public void setImage() {
        Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("sekolah-tinggi-klang-logo-DBDC58156C-seeklogo.com.png"));
        ImageIcon icon = new ImageIcon(image);
        setIconImage(icon.getImage());

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CandidateRegLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton voteBack;
    private javax.swing.JButton voteSave;
    // End of variables declaration//GEN-END:variables
}
