/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.PibgVoteApp;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static my.PibgVoteApp.MainMenuGUI.VoterListHolder.voterlist;

/**
 *
 * @author User
 */
public class VoterRegister extends javax.swing.JFrame {

    private static VoterRegister voterRegisterInstance;

    /**
     * Creates new form VoteGUI
     */
    public VoterRegister() {
        initComponents();
        setImage();
        voterRegisterInstance = this;
    }

    @Override
    protected void processWindowEvent(WindowEvent e) {
        if (e.getID() == WindowEvent.WINDOW_CLOSING) {
            // prevent the window from being closed
            Object[] options = {"OK"};
            JOptionPane.showOptionDialog(this, "You are not allowed to exit!", "NO EXIT",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
                    null, options, options[0]);
            return;
        }
        super.processWindowEvent(e);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voteRCfm = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        voteCfmSaveBtn = new javax.swing.JButton();
        voteCfmBackBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNameVoter = new javax.swing.JLabel();
        textICvoter = new javax.swing.JLabel();
        voteRCfmSaved = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        voteRBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNameRVoter = new javax.swing.JTextField();
        txtICRvoter = new javax.swing.JTextField();
        voteRSaveBtn = new javax.swing.JButton();
        voteRBackBtn = new javax.swing.JButton();
        icLbl = new javax.swing.JLabel();

        voteRCfm.setTitle("Confirmation");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("Vote Registration Confirmation");

        voteCfmSaveBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        voteCfmSaveBtn.setText("Save");
        voteCfmSaveBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        voteCfmSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voteCfmSaveBtnActionPerformed(evt);
            }
        });

        voteCfmBackBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        voteCfmBackBtn.setText("Back");
        voteCfmBackBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        voteCfmBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voteCfmBackBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("I/C No:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Name:");

        txtNameVoter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textICvoter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout voteRCfmLayout = new javax.swing.GroupLayout(voteRCfm.getContentPane());
        voteRCfm.getContentPane().setLayout(voteRCfmLayout);
        voteRCfmLayout.setHorizontalGroup(
            voteRCfmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(voteRCfmLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(voteRCfmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(voteRCfmLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textICvoter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(voteRCfmLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNameVoter, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(voteRCfmLayout.createSequentialGroup()
                        .addComponent(voteCfmBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voteCfmSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        voteRCfmLayout.setVerticalGroup(
            voteRCfmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(voteRCfmLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(voteRCfmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNameVoter, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(voteRCfmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textICvoter, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(voteRCfmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voteCfmBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voteCfmSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        voteRCfmSaved.setTitle("Saved");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("Your information has been saved!");

        voteRBtn.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        voteRBtn.setText("OK!");
        voteRBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        voteRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voteRBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout voteRCfmSavedLayout = new javax.swing.GroupLayout(voteRCfmSaved.getContentPane());
        voteRCfmSaved.getContentPane().setLayout(voteRCfmSavedLayout);
        voteRCfmSavedLayout.setHorizontalGroup(
            voteRCfmSavedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(voteRCfmSavedLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(voteRCfmSavedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, voteRCfmSavedLayout.createSequentialGroup()
                        .addComponent(voteRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, voteRCfmSavedLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(30, 30, 30))))
        );
        voteRCfmSavedLayout.setVerticalGroup(
            voteRCfmSavedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, voteRCfmSavedLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(voteRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Voter Registration");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Vote Registration");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("I/C No:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Name:");

        txtNameRVoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameRVoterActionPerformed(evt);
            }
        });

        txtICRvoter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtICRvoterKeyPressed(evt);
            }
        });

        voteRSaveBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        voteRSaveBtn.setText("Save");
        voteRSaveBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        voteRSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voteRSaveBtnActionPerformed(evt);
            }
        });

        voteRBackBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        voteRBackBtn.setText("Back");
        voteRBackBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        voteRBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voteRBackBtnActionPerformed(evt);
            }
        });

        icLbl.setForeground(new java.awt.Color(255, 0, 51));
        icLbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                icLblKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(voteRBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(voteRSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNameRVoter, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtICRvoter, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(icLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNameRVoter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtICRvoter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voteRBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voteRSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voteRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteRBtnActionPerformed
        // TODO add your handling code here:
        voteRCfmSaved.setVisible(false);
        new MainMenuGUI().setVisible(true);
    }//GEN-LAST:event_voteRBtnActionPerformed

    private void voteRBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteRBackBtnActionPerformed
        // TODO add your handling code here:
        VoterRegister.closeVoterRegister();
        new MainMenuGUI().setVisible(true);

    }//GEN-LAST:event_voteRBackBtnActionPerformed

    private void voteRSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteRSaveBtnActionPerformed
        // TODO add your handling code here:
        if (txtNameRVoter.getText().isEmpty() || txtICRvoter.getText().isEmpty()) {
            Object[] options = {"OK"};
            JOptionPane.showOptionDialog(this, "Please fill in all fields", "Error",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
                    null, options, options[0]);

        } else {
            String nameText = txtNameRVoter.getText();
            String icText = txtICRvoter.getText();
            String votedText = "-";
            String nameTextModified = nameText.trim().toLowerCase();
            String icTextModified = icText.trim().toLowerCase();

            // check if a voter with the same name and IC already exists in the list
            boolean duplicate = false;
            for (Voter v : voterlist) {
                if (v.getName().toLowerCase().trim().equals(nameTextModified) && v.getIcNo().toLowerCase().trim().equals(icTextModified)) {
                    duplicate = true;
                    break;
                }
            }

            if (duplicate) {
                // display option pane saying there is already a record of voter registered
                Object[] options = {"OK"};
                JOptionPane.showOptionDialog(this, "Voter already registered", "Duplicate", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
                        null, options, options[0]);
                txtNameRVoter.setText("");
                txtICRvoter.setText("");
            } else {
                txtNameVoter.setText(nameText);
                textICvoter.setText(icText);
                VoterRegister.closeVoterRegister();
                voteRCfm.setVisible(true);
                voteRCfm.setSize(415, 300);
                voteRCfm.setLocationRelativeTo(null);
            }
        }
    }//GEN-LAST:event_voteRSaveBtnActionPerformed

    private void voteCfmBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteCfmBackBtnActionPerformed
        // TODO add your handling code here:

        voteRCfm.setVisible(false);
        new VoterRegister().setVisible(true);
    }//GEN-LAST:event_voteCfmBackBtnActionPerformed

    private void voteCfmSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteCfmSaveBtnActionPerformed
        // TODO add your handling code here:
        String nameText = txtNameRVoter.getText();
        String icText = txtICRvoter.getText();
        String votedText = "-";

        FileWriter writer;
        try {
            writer = new FileWriter("Voter.txt", true);
            writer.append(nameText + "," + icText + "," + votedText + "\n");
            writer.close();
            // create new candidate object
            Voter voter = new Voter(nameText, icText, votedText);
            voterlist.add(voter);
            VoterRegister.closeVoterRegister();

        } catch (IOException ex) {
            Logger.getLogger(CandidateReg.class.getName()).log(Level.SEVERE, null, ex);
        }
        voteRCfm.setVisible(false);
        voteRCfmSaved.setVisible(true);
        voteRCfmSaved.setSize(341, 163);
        voteRCfmSaved.setLocationRelativeTo(null);

    }//GEN-LAST:event_voteCfmSaveBtnActionPerformed

    private void txtNameRVoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameRVoterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameRVoterActionPerformed

    private void icLblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_icLblKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_icLblKeyPressed

    private void txtICRvoterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtICRvoterKeyPressed
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if (Character.isDigit(ch) || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE) {
            txtICRvoter.setEditable(true);
            icLbl.setText("");
        } else {
            txtICRvoter.setEditable(false);
            icLbl.setText("Please Enter Numbers Only!");
        }
    }//GEN-LAST:event_txtICRvoterKeyPressed

    public static void closeVoterRegister() {
        voterRegisterInstance.setVisible(false);
    }

    public void setImage() {
        Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("sekolah-tinggi-klang-logo-DBDC58156C-seeklogo.com.png"));
        ImageIcon icon = new ImageIcon(image);
        setIconImage(icon.getImage());
        voteRCfmSaved.setIconImage(icon.getImage());
        voteRCfm.setIconImage(icon.getImage());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel textICvoter;
    private javax.swing.JTextField txtICRvoter;
    private javax.swing.JTextField txtNameRVoter;
    private javax.swing.JLabel txtNameVoter;
    private javax.swing.JButton voteCfmBackBtn;
    private javax.swing.JButton voteCfmSaveBtn;
    private javax.swing.JButton voteRBackBtn;
    private javax.swing.JButton voteRBtn;
    private javax.swing.JDialog voteRCfm;
    private javax.swing.JDialog voteRCfmSaved;
    private javax.swing.JButton voteRSaveBtn;
    // End of variables declaration//GEN-END:variables
}
